name: Clippy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/clippy.yml
      - captions/**

jobs:
  clippy:
    uses: winstxnhdw/actions/.github/workflows/rust.yml@main
    with:
      working-directory: captions
      disable-test: true
